add_newline = true #ã‚³ãƒãƒ³ãƒ‰ãƒ—ãƒ­ãƒ³ãƒˆã®é–“ã«ç©ºè¡Œã‚’è¿½åŠ 

scan_timeout = 10 #ã‚¿ã‚¤ãƒ ã‚¢ã‚¦ãƒˆæ™‚é–“ã‚’è¨­å®š

# Battery
[battery]
format = "[$symbol$percentage]($style) "
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "

# Very Low
[[battery.display]]
threshold = 10
style = "bold red"

# Low
[[battery.display]]
threshold = 30
style = "bold yellow"

# High
[[battery.display]]
threshold = 100
style = "bold green"

# Character
[character]
success_symbol = "[âœ](bold green)" # ã‚³ãƒãƒ³ãƒ‰æˆåŠŸæ™‚
error_symbol = "[âœ—](bold red)"    # ã‚³ãƒãƒ³ãƒ‰å¤±æ•—æ™‚

# Memory
[memory_usage]
format = "[$symbol$percentage]($style) "
disabled = false
threshold = -1
symbol = " "
style = "bold green"

# time
[time]
disabled = false
format = '[$time]($style) '
style = "bold green"
time_format = "%R"

# sudo
[sudo]
style = "bold green"
symbol = "ğŸ‘©â€ğŸ’» "
disabled = false