# ã‚·ã‚§ãƒ«ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®é–“ã«ç©ºè¡Œã‚’è¿½åŠ ã—ã¾ã™
add_newline = true

# ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«ã‚’ç„¡åŠ¹ã«ã—ã€ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã‹ã‚‰å®Œå…¨ã«éš ã—ã¾ã™
[package]
disabled = true

# ã‚¿ã‚¤ãƒ ã‚¢ã‚¦ãƒˆæ™‚é–“
scan_timeout = 10

# ãƒãƒƒãƒ†ãƒªãƒ¼
[battery]
format = "[$symbol$percentage]($style) "
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

# Character
[character]
success_symbol = "[âœ](bold green)" # ã‚³ãƒãƒ³ãƒ‰æˆåŠŸæ™‚
error_symbol = "[âœ—](bold red)"    # ã‚³ãƒãƒ³ãƒ‰å¤±æ•—æ™‚

[memory_usage]
format = "[$symbol$percentage]($style) "
disabled = false
threshold = -1
symbol = " "
style = "bold green"

[time]
disabled = false
format = '[$time]($style) '
style = "bold green"
time_format = "%R"

[sudo]
style = "bold green"
symbol = "ğŸ‘©â€ğŸ’» "
disabled = false
# ã‚·ã‚§ãƒ«ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®é–“ã«ç©ºè¡Œã‚’è¿½åŠ ã—ã¾ã™
add_newline = true

# ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«ã‚’ç„¡åŠ¹ã«ã—ã€ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã‹ã‚‰å®Œå…¨ã«éš ã—ã¾ã™
[package]
disabled = true

# ã‚¿ã‚¤ãƒ ã‚¢ã‚¦ãƒˆæ™‚é–“
scan_timeout = 10

# ãƒãƒƒãƒ†ãƒªãƒ¼
[battery]
format = "[$symbol$percentage]($style) "
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

# Character
[character]
success_symbol = "[âœ](bold green)" # ã‚³ãƒãƒ³ãƒ‰æˆåŠŸæ™‚
error_symbol = "[âœ—](bold red)"    # ã‚³ãƒãƒ³ãƒ‰å¤±æ•—æ™‚

[memory_usage]
format = "[$symbol$percentage]($style) "
disabled = false
threshold = -1
symbol = " "
style = "bold green"

[time]
disabled = false
format = '[$time]($style) '
style = "bold green"
time_format = "%R"

[sudo]
style = "bold green"
symbol = "ğŸ‘©â€ğŸ’» "
disabled = false
